#include "core/opcode.h"
#include "core/cpu.h"

const Opcode OPCODES[256] = {
	{nullptr, "BRK", 1, 7, AddressingMode::NONE_ADDRESSING},   // 0x00
	{&CPU::ora, "ORA", 2, 6, AddressingMode::INDIRECT_X},	   // 0x01
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x02
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x03
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x04
	{&CPU::ora, "ORA", 2, 3, AddressingMode::ZERO_PAGE},	   // 0x05
	{&CPU::asl, "ASL", 2, 5, AddressingMode::ZERO_PAGE},	   // 0x06
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x07
	{&CPU::php, "PHP", 1, 3, AddressingMode::NONE_ADDRESSING}, // 0x08
	{&CPU::ora, "ORA", 2, 2, AddressingMode::IMMEDIATE},	   // 0x09
	{&CPU::asl, "ASL", 1, 2, AddressingMode::NONE_ADDRESSING}, // 0x0A
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x0B
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x0C
	{&CPU::ora, "ORA", 3, 4, AddressingMode::ABSOLUTE},		   // 0x0D
	{&CPU::asl, "ASL", 3, 6, AddressingMode::ABSOLUTE},		   // 0x0E
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x0F
	{&CPU::bpl, "BPL", 2, 2, AddressingMode::NONE_ADDRESSING}, // 0x10
	{&CPU::ora, "ORA", 2, 5, AddressingMode::INDIRECT_Y},	   // 0x11
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x12
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x13
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x14
	{&CPU::ora, "ORA", 2, 4, AddressingMode::ZERO_PAGE_X},	   // 0x15
	{&CPU::asl, "ASL", 2, 6, AddressingMode::ZERO_PAGE_X},	   // 0x16
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x17
	{&CPU::clc, "CLC", 1, 2, AddressingMode::NONE_ADDRESSING}, // 0x18
	{&CPU::ora, "ORA", 3, 4, AddressingMode::ABSOLUTE_Y},	   // 0x19
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x1A
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x1B
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x1C
	{&CPU::ora, "ORA", 3, 4, AddressingMode::ABSOLUTE_X},	   // 0x1D
	{&CPU::asl, "ASL", 3, 7, AddressingMode::ABSOLUTE_X},	   // 0x1E
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x1F
	{&CPU::jsr, "JSR", 3, 6, AddressingMode::ABSOLUTE},		   // 0x20
	{&CPU::and_op, "AND", 2, 6, AddressingMode::INDIRECT_X},   // 0x21
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x22
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x23
	{&CPU::bit, "BIT", 2, 3, AddressingMode::ZERO_PAGE},	   // 0x24
	{&CPU::and_op, "AND", 2, 3, AddressingMode::ZERO_PAGE},	   // 0x25
	{&CPU::rol, "ROL", 2, 5, AddressingMode::ZERO_PAGE},	   // 0x26
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x27
	{&CPU::plp, "PLP", 1, 4, AddressingMode::NONE_ADDRESSING}, // 0x28
	{&CPU::and_op, "AND", 2, 2, AddressingMode::IMMEDIATE},	   // 0x29
	{&CPU::rol, "ROL", 1, 2, AddressingMode::NONE_ADDRESSING}, // 0x2A
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x2B
	{&CPU::bit, "BIT", 3, 4, AddressingMode::ABSOLUTE},		   // 0x2C
	{&CPU::and_op, "AND", 3, 4, AddressingMode::ABSOLUTE},	   // 0x2D
	{&CPU::rol, "ROL", 3, 6, AddressingMode::ABSOLUTE},		   // 0x2E
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x2F
	{&CPU::bmi, "BMI", 2, 2, AddressingMode::NONE_ADDRESSING}, // 0x30
	{&CPU::and_op, "AND", 2, 5, AddressingMode::INDIRECT_Y},   // 0x31
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x32
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x33
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x34
	{&CPU::and_op, "AND", 2, 4, AddressingMode::ZERO_PAGE_X},  // 0x35
	{&CPU::rol, "ROL", 2, 6, AddressingMode::ZERO_PAGE_X},	   // 0x36
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x37
	{&CPU::sec, "SEC", 1, 2, AddressingMode::NONE_ADDRESSING}, // 0x38
	{&CPU::and_op, "AND", 3, 4, AddressingMode::ABSOLUTE_Y},   // 0x39
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x3A
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x3B
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x3C
	{&CPU::and_op, "AND", 3, 4, AddressingMode::ABSOLUTE_X},   // 0x3D
	{&CPU::rol, "ROL", 3, 7, AddressingMode::ABSOLUTE_X},	   // 0x3E
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x3F
	{&CPU::rti, "RTI", 1, 6, AddressingMode::NONE_ADDRESSING}, // 0x40
	{&CPU::eor, "EOR", 2, 6, AddressingMode::INDIRECT_X},	   // 0x41
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x42
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x43
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x44
	{&CPU::eor, "EOR", 2, 3, AddressingMode::ZERO_PAGE},	   // 0x45
	{&CPU::lsr, "LSR", 2, 5, AddressingMode::ZERO_PAGE},	   // 0x46
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x47
	{&CPU::pha, "PHA", 1, 3, AddressingMode::NONE_ADDRESSING}, // 0x48
	{&CPU::eor, "EOR", 2, 2, AddressingMode::IMMEDIATE},	   // 0x49
	{&CPU::lsr, "LSR", 1, 2, AddressingMode::NONE_ADDRESSING}, // 0x4A
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x4B
	{&CPU::jmp, "JMP", 3, 3, AddressingMode::ABSOLUTE},		   // 0x4C
	{&CPU::eor, "EOR", 3, 4, AddressingMode::ABSOLUTE},		   // 0x4D
	{&CPU::lsr, "LSR", 3, 6, AddressingMode::ABSOLUTE},		   // 0x4E
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x4F
	{&CPU::bvc, "BVC", 2, 2, AddressingMode::NONE_ADDRESSING}, // 0x50
	{&CPU::eor, "EOR", 2, 5, AddressingMode::INDIRECT_Y},	   // 0x51
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x52
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x53
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x54
	{&CPU::eor, "EOR", 2, 4, AddressingMode::ZERO_PAGE_X},	   // 0x55
	{&CPU::lsr, "LSR", 2, 6, AddressingMode::ZERO_PAGE_X},	   // 0x56
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x57
	{&CPU::cli, "CLI", 1, 2, AddressingMode::NONE_ADDRESSING}, // 0x58
	{&CPU::eor, "EOR", 3, 4, AddressingMode::ABSOLUTE_Y},	   // 0x59
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x5A
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x5B
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x5C
	{&CPU::eor, "EOR", 3, 4, AddressingMode::ABSOLUTE_X},	   // 0x5D
	{&CPU::lsr, "LSR", 3, 7, AddressingMode::ABSOLUTE_X},	   // 0x5E
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x5F
	{&CPU::rts, "RTS", 1, 6, AddressingMode::NONE_ADDRESSING}, // 0x60
	{&CPU::adc, "ADC", 2, 6, AddressingMode::INDIRECT_X},	   // 0x61
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x62
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x63
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x64
	{&CPU::adc, "ADC", 2, 3, AddressingMode::ZERO_PAGE},	   // 0x65
	{&CPU::ror, "ROR", 2, 5, AddressingMode::ZERO_PAGE},	   // 0x66
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x67
	{&CPU::pla, "PLA", 1, 4, AddressingMode::NONE_ADDRESSING}, // 0x68
	{&CPU::adc, "ADC", 2, 2, AddressingMode::IMMEDIATE},	   // 0x69
	{&CPU::ror, "ROR", 1, 2, AddressingMode::NONE_ADDRESSING}, // 0x6A
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x6B
	{&CPU::jmp, "JMP", 3, 5, AddressingMode::NONE_ADDRESSING}, // 0x6C
	{&CPU::adc, "ADC", 3, 4, AddressingMode::ABSOLUTE},		   // 0x6D
	{&CPU::ror, "ROR", 3, 6, AddressingMode::ABSOLUTE},		   // 0x6E
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x6F
	{&CPU::bvs, "BVS", 2, 2, AddressingMode::NONE_ADDRESSING}, // 0x70
	{&CPU::adc, "ADC", 2, 5, AddressingMode::INDIRECT_Y},	   // 0x71
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x72
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x73
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x74
	{&CPU::adc, "ADC", 2, 4, AddressingMode::ZERO_PAGE_X},	   // 0x75
	{&CPU::ror, "ROR", 2, 6, AddressingMode::ZERO_PAGE_X},	   // 0x76
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x77
	{&CPU::sei, "SEI", 1, 2, AddressingMode::NONE_ADDRESSING}, // 0x78
	{&CPU::adc, "ADC", 3, 4, AddressingMode::ABSOLUTE_Y},	   // 0x79
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x7A
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x7B
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x7C
	{&CPU::adc, "ADC", 3, 4, AddressingMode::ABSOLUTE_X},	   // 0x7D
	{&CPU::ror, "ROR", 3, 7, AddressingMode::ABSOLUTE_X},	   // 0x7E
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x7F
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x80
	{&CPU::sta, "STA", 2, 6, AddressingMode::INDIRECT_X},	   // 0x81
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x82
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x83
	{&CPU::sty, "STY", 2, 3, AddressingMode::ZERO_PAGE},	   // 0x84
	{&CPU::sta, "STA", 2, 3, AddressingMode::ZERO_PAGE},	   // 0x85
	{&CPU::stx, "STX", 2, 3, AddressingMode::ZERO_PAGE},	   // 0x86
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x87
	{&CPU::dey, "DEY", 1, 2, AddressingMode::NONE_ADDRESSING}, // 0x88
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x89
	{&CPU::txa, "TXA", 1, 2, AddressingMode::NONE_ADDRESSING}, // 0x8A
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x8B
	{&CPU::sty, "STY", 3, 4, AddressingMode::ABSOLUTE},		   // 0x8C
	{&CPU::sta, "STA", 3, 4, AddressingMode::ABSOLUTE},		   // 0x8D
	{&CPU::stx, "STX", 3, 4, AddressingMode::ABSOLUTE},		   // 0x8E
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x8F
	{&CPU::bcc, "BCC", 2, 2, AddressingMode::NONE_ADDRESSING}, // 0x90
	{&CPU::sta, "STA", 2, 6, AddressingMode::INDIRECT_Y},	   // 0x91
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x92
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x93
	{&CPU::sty, "STY", 2, 4, AddressingMode::ZERO_PAGE_X},	   // 0x94
	{&CPU::sta, "STA", 2, 4, AddressingMode::ZERO_PAGE_X},	   // 0x95
	{&CPU::stx, "STX", 2, 4, AddressingMode::ZERO_PAGE_Y},	   // 0x96
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x97
	{&CPU::tya, "TYA", 1, 2, AddressingMode::NONE_ADDRESSING}, // 0x98
	{&CPU::sta, "STA", 3, 5, AddressingMode::ABSOLUTE_Y},	   // 0x99
	{&CPU::txs, "TXS", 1, 2, AddressingMode::NONE_ADDRESSING}, // 0x9A
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x9B
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x9C
	{&CPU::sta, "STA", 3, 5, AddressingMode::ABSOLUTE_X},	   // 0x9D
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x9E
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0x9F
	{&CPU::ldy, "LDY", 2, 2, AddressingMode::IMMEDIATE},	   // 0xA0
	{&CPU::lda, "LDA", 2, 6, AddressingMode::INDIRECT_X},	   // 0xA1
	{&CPU::ldx, "LDX", 2, 2, AddressingMode::IMMEDIATE},	   // 0xA2
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0xA3
	{&CPU::ldy, "LDY", 2, 3, AddressingMode::ZERO_PAGE},	   // 0xA4
	{&CPU::lda, "LDA", 2, 3, AddressingMode::ZERO_PAGE},	   // 0xA5
	{&CPU::ldx, "LDX", 2, 3, AddressingMode::ZERO_PAGE},	   // 0xA6
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0xA7
	{&CPU::tay, "TAY", 1, 2, AddressingMode::NONE_ADDRESSING}, // 0xA8
	{&CPU::lda, "LDA", 2, 2, AddressingMode::IMMEDIATE},	   // 0xA9
	{&CPU::tax, "TAX", 1, 2, AddressingMode::NONE_ADDRESSING}, // 0xAA
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0xAB
	{&CPU::ldy, "LDY", 3, 4, AddressingMode::ABSOLUTE},		   // 0xAC
	{&CPU::lda, "LDA", 3, 4, AddressingMode::ABSOLUTE},		   // 0xAD
	{&CPU::ldx, "LDX", 3, 4, AddressingMode::ABSOLUTE},		   // 0xAE
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0xAF
	{&CPU::bcs, "BCS", 2, 2, AddressingMode::NONE_ADDRESSING}, // 0xB0
	{&CPU::lda, "LDA", 2, 5, AddressingMode::INDIRECT_Y},	   // 0xB1
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0xB2
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0xB3
	{&CPU::ldy, "LDY", 2, 4, AddressingMode::ZERO_PAGE_X},	   // 0xB4
	{&CPU::lda, "LDA", 2, 4, AddressingMode::ZERO_PAGE_X},	   // 0xB5
	{&CPU::ldx, "LDX", 2, 4, AddressingMode::ZERO_PAGE_Y},	   // 0xB6
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0xB7
	{&CPU::clv, "CLV", 1, 2, AddressingMode::NONE_ADDRESSING}, // 0xB8
	{&CPU::lda, "LDA", 3, 4, AddressingMode::ABSOLUTE_Y},	   // 0xB9
	{&CPU::tsx, "TSX", 1, 2, AddressingMode::NONE_ADDRESSING}, // 0xBA
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0xBB
	{&CPU::ldy, "LDY", 3, 4, AddressingMode::ABSOLUTE_X},	   // 0xBC
	{&CPU::lda, "LDA", 3, 4, AddressingMode::ABSOLUTE_X},	   // 0xBD
	{&CPU::ldx, "LDX", 3, 4, AddressingMode::ABSOLUTE_Y},	   // 0xBE
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0xBF
	{&CPU::cpy, "CPY", 2, 2, AddressingMode::IMMEDIATE},	   // 0xC0
	{&CPU::cmp, "CMP", 2, 6, AddressingMode::INDIRECT_X},	   // 0xC1
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0xC2
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0xC3
	{&CPU::cpy, "CPY", 2, 3, AddressingMode::ZERO_PAGE},	   // 0xC4
	{&CPU::cmp, "CMP", 2, 3, AddressingMode::ZERO_PAGE},	   // 0xC5
	{&CPU::dec, "DEC", 2, 5, AddressingMode::ZERO_PAGE},	   // 0xC6
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0xC7
	{&CPU::iny, "INY", 1, 2, AddressingMode::NONE_ADDRESSING}, // 0xC8
	{&CPU::cmp, "CMP", 2, 2, AddressingMode::IMMEDIATE},	   // 0xC9
	{&CPU::dex, "DEX", 1, 2, AddressingMode::NONE_ADDRESSING}, // 0xCA
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0xCB
	{&CPU::cpy, "CPY", 3, 4, AddressingMode::ABSOLUTE},		   // 0xCC
	{&CPU::cmp, "CMP", 3, 4, AddressingMode::ABSOLUTE},		   // 0xCD
	{&CPU::dec, "DEC", 3, 6, AddressingMode::ABSOLUTE},		   // 0xCE
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0xCF
	{&CPU::bne, "BNE", 2, 2, AddressingMode::NONE_ADDRESSING}, // 0xD0
	{&CPU::cmp, "CMP", 2, 5, AddressingMode::INDIRECT_Y},	   // 0xD1
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0xD2
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0xD3
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0xD4
	{&CPU::cmp, "CMP", 2, 4, AddressingMode::ZERO_PAGE_X},	   // 0xD5
	{&CPU::dec, "DEC", 2, 6, AddressingMode::ZERO_PAGE_X},	   // 0xD6
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0xD7
	{&CPU::cld, "CLD", 1, 2, AddressingMode::NONE_ADDRESSING}, // 0xD8
	{&CPU::cmp, "CMP", 3, 4, AddressingMode::ABSOLUTE_Y},	   // 0xD9
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0xDA
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0xDB
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0xDC
	{&CPU::cmp, "CMP", 3, 4, AddressingMode::ABSOLUTE_X},	   // 0xDD
	{&CPU::dec, "DEC", 3, 7, AddressingMode::ABSOLUTE_X},	   // 0xDE
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0xDF
	{&CPU::cpx, "CPX", 2, 2, AddressingMode::IMMEDIATE},	   // 0xE0
	{&CPU::sbc, "SBC", 2, 6, AddressingMode::INDIRECT_X},	   // 0xE1
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0xE2
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0xE3
	{&CPU::cpx, "CPX", 2, 3, AddressingMode::ZERO_PAGE},	   // 0xE4
	{&CPU::sbc, "SBC", 2, 3, AddressingMode::ZERO_PAGE},	   // 0xE5
	{&CPU::inc, "INC", 2, 5, AddressingMode::ZERO_PAGE},	   // 0xE6
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0xE7
	{&CPU::inx, "INX", 1, 2, AddressingMode::NONE_ADDRESSING}, // 0xE8
	{&CPU::sbc, "SBC", 2, 2, AddressingMode::IMMEDIATE},	   // 0xE9
	{nullptr, "NOP", 1, 2, AddressingMode::NONE_ADDRESSING},   // 0xEA
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0xEB
	{&CPU::cpx, "CPX", 3, 4, AddressingMode::ABSOLUTE},		   // 0xEC
	{&CPU::sbc, "SBC", 3, 4, AddressingMode::ABSOLUTE},		   // 0xED
	{&CPU::inc, "INC", 3, 6, AddressingMode::ABSOLUTE},		   // 0xEE
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0xEF
	{&CPU::beq, "BEQ", 2, 2, AddressingMode::NONE_ADDRESSING}, // 0xF0
	{&CPU::sbc, "SBC", 2, 5, AddressingMode::INDIRECT_Y},	   // 0xF1
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0xF2
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0xF3
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0xF4
	{&CPU::sbc, "SBC", 2, 4, AddressingMode::ZERO_PAGE_X},	   // 0xF5
	{&CPU::inc, "INC", 2, 6, AddressingMode::ZERO_PAGE_X},	   // 0xF6
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0xF7
	{&CPU::sed, "SED", 1, 2, AddressingMode::NONE_ADDRESSING}, // 0xF8
	{&CPU::sbc, "SBC", 3, 4, AddressingMode::ABSOLUTE_Y},	   // 0xF9
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0xFA
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0xFB
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING},	   // 0xFC
	{&CPU::sbc, "SBC", 3, 4, AddressingMode::ABSOLUTE_X},	   // 0xFD
	{&CPU::inc, "INC", 3, 7, AddressingMode::ABSOLUTE_X},	   // 0xFE
	{nullptr, "", 0, 0, AddressingMode::NONE_ADDRESSING}	   // 0xFF

};